import React, { useRef } from 'react'
import useOnScreen from '../13. useEventListener/useOnScreen'

export default function OnScreenComponent() {
  const headerRef = useRef()
  const visible = useOnScreen(headerRef, "-100px")
  
  return (
    <>
      <h1>Header 1</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est ea, sit voluptates, minima pariatur recusandae magni velit qui quibusdam ipsa sequi suscipit aliquid aspernatur ipsum, porro facere praesentium quaerat corporis maxime nam adipisci repudiandae tempora explicabo! Expedita numquam neque natus ducimus excepturi vero nemo sapiente eos ad officiis error earum in labore assumenda nulla laudantium, temporibus culpa, aspernatur omnis aperiam facilis iste dicta. Suscipit ut eaque ullam sed exercitationem, et optio voluptatem aperiam voluptate ipsam cupiditate voluptatibus nisi, odit assumenda reprehenderit perferendis dolores. Odio quos quasi officia beatae dicta dolorum veritatis fuga harum nemo similique magnam laudantium obcaecati sequi inventore aliquid fugit voluptatum adipisci, qui voluptates reiciendis ipsa dolores quas. Recusandae animi nisi provident sint, dignissimos, voluptates quis perferendis ex deleniti atque aspernatur nemo dolorum. Incidunt, inventore dolores! Sint iste necessitatibus nihil cumque non quam ducimus, voluptas vero quidem? Quae ipsa possimus, labore sequi officiis dolores deleniti dolor officia sit voluptatem aspernatur ea dolorem. Mollitia, accusamus culpa, est temporibus hic excepturi alias aliquid distinctio tempora saepe accusantium animi, impedit vel exercitationem. Quasi, officia modi nulla temporibus repellendus laboriosam sapiente accusamus neque quia quibusdam atque magnam id asperiores fugit quo placeat sint corrupti dolore eligendi ad. Perferendis quas rem quos, voluptates iure earum suscipit eaque nemo laudantium dicta, nihil atque in magni voluptatem quidem, necessitatibus eveniet illo perspiciatis quaerat labore. Sint nostrum magnam debitis, dicta repellendus quo molestiae ab maxime inventore ipsa, consequatur amet? Perferendis modi blanditiis provident est aspernatur commodi? Numquam dolores aut rem non nesciunt illum consectetur. Quaerat dolore accusantium laboriosam ipsa alias, ipsam voluptatum corrupti blanditiis magnam, provident tempora exercitationem nobis eaque aut nisi, doloribus fuga enim dolor eos maiores. In doloribus tenetur inventore magnam itaque accusantium soluta hic aliquid tempora! Animi a eius sed dolorem dolor quae? Corrupti molestiae tenetur natus reprehenderit quam tempore neque dignissimos architecto?</p>
      <h2 ref={headerRef}>Header 2 {visible && "(Visible)"}</h2>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error asperiores qui doloremque quaerat maxime eveniet illum nulla? Excepturi, iusto. Dolorum saepe iste natus cupiditate perspiciatis voluptatibus consequuntur, quas provident officia ea, vel a, quasi sequi pariatur. Iure architecto soluta, ipsum eveniet assumenda earum eligendi sequi est incidunt obcaecati quibusdam at ea totam harum sapiente dignissimos atque cupiditate. Optio ad vel blanditiis perspiciatis quo facilis numquam est eaque facere placeat quas distinctio nobis cum beatae provident dolores, a accusamus odio temporibus quis rem sequi consectetur dolore aliquam. Quidem architecto voluptatem qui tempore mollitia quaerat consequatur cumque, suscipit, velit porro dolor facilis fuga soluta dicta debitis! Sint, similique incidunt libero alias rem expedita neque assumenda, aliquam harum beatae, iste ipsam numquam blanditiis iusto laboriosam! Repellendus error maiores, amet veritatis explicabo quasi? Repudiandae commodi facilis architecto assumenda inventore fugit magnam atque ipsa libero beatae quia, corrupti ipsum! Fugiat et a adipisci nam! Repudiandae delectus quaerat minus quos. Nemo magni libero minus est delectus! Rem non, voluptatum dolorum veritatis aspernatur inventore ea? Soluta veritatis quisquam fuga voluptatum impedit fugit eius ipsum unde laboriosam recusandae, rem explicabo. Modi eaque quos non quasi, magnam impedit facilis quas dolorem possimus dolores maxime provident voluptatem exercitationem nostrum omnis aperiam debitis tempore doloremque? Magnam sequi quaerat, dolorem, velit voluptas ullam tempora doloremque autem eius necessitatibus dicta, nesciunt quia non quod laborum reprehenderit neque sunt ea fuga esse nisi sit enim molestiae? Nisi fugit modi similique! Necessitatibus voluptatum architecto iusto nemo, neque cum voluptatibus quo id quos earum in deleniti excepturi iste modi corrupti qui error labore. Id, iure odit! Tenetur repellendus, ex quod maiores labore nemo voluptatem explicabo iure, exercitationem asperiores modi veritatis, commodi dolores earum ut eum iusto quia? Quos laudantium corrupti voluptatum ab nesciunt. Nesciunt accusamus debitis reprehenderit ducimus saepe officia repudiandae, praesentium dolorum dolorem aut facilis?</p>
    </>
  )
}
